[package]
name = "petal"
version = "0.1.0"
edition = "2021"

[dependencies]
rug = "1.15.0"
structopt = "0.3.26"
petal_syntax = { path = "petal_syntax" }

[dev-dependencies]
k9 = {path = "/Users/ian/src/k9/k9"}
